### ISSUE TITLE
SSL Self-Sign Cert

### ISSUE THREAD

**Issue by jdc1898** [silinternational/crashplan-php-client#1]
Is there a way to incorporate the CURL option to accept self-signed certs?

**Comment by fillup** [comment]
Yes probably, I'll look into it and see if I can get that added.

**Comment by jdc1898** [comment]
Awesome! I work for a large ISP/MSP in SE Louisiana. I'm hoping to use this code in some automation. If successful, I will certainly fork a release and contribute to the project. Looks promising!

On Jul 10, 2015, at 7:43 PM, Phillip Shipley <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes probably, I'll look into it and see if I can get that added.

##

**Comment by fillup** [comment]
Actually you can use a custom CA or cert with it already. When you provide a config array to the constructor you can pass any normal GuzzleHttp\Client configuration directives under the `http_client_options` array element. Check out https://github.com/silinternational/crashplan-php-client/blob/master/src/Client.php#L58 to see where it looks for that property and then passes it into creating the guzzle http client. You should be able to do what you need with something like:

``` php
<?php

use Crashplan\Client;

$client = new Client([
  'apiuser' => 'username',
  'apipass' => 'password',
  'http_client_config' => [
      'defaults' => [
          'verify' => '/path/to/cert.crt',
      ],
  ],
]);
```

The Guzzle docs for the `verify` option are here: http://docs.guzzlephp.org/en/5.3/clients.html#verify

Give that a try and let me know if that works for you. And it would be awesome if you want to submit a PR adding more API support. Thanks.

**Comment by fillup** [comment]
@jdc1898 Hi David, did you get a chance to try that out?
